from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# Create a router and register the UserViewSet with it
router = DefaultRouter()
router.register(r'users', views.UserViewSet)

from django.urls import path, include  # Import include here

urlpatterns = [
    path("home/", views.home),  # Added "/" to match consistency
    path("", views.home),
    path("join/", views.join, name="join"),
    # Include the URLs generated by the router
    path("api/", include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),  # Removed namespace
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),


]
